### ISSUE TITLE
Need 2019 support? 

### ISSUE THREAD

**Issue by ackleymi** [Forestmb/goff#1]
Do we need to make any modifications to constants/code structs this year to support the 2019 season?

**Comment by Forestmb** [comment]
Yes, each football season gets assigned a unique ID and we need to update our [internal mapping](https://github.com/Forestmb/goff/blob/3bbb8ff7688e0e06edcd89d35d2d72c9ddb1f660/fantasy.go#L93) to allow users of the client to query for information based on the calendar year.

I haven't found a way to predict what the game ID will be until after it has been generated. I would really like for it to automatically discover/update the game IDs as they become available. In lieu of that, I should at least document how to go about finding and updating the game ID map as every year I have to remember what I did last time. I thought you used to be able to pull it from the URL of your league page, but this time I had to use the `debug` client provided by this package:

```
Enter URL: https://fantasysports.yahooapis.com/fantasy/v2/game/nfl
Response:
<?xml version="1.0" encoding="UTF-8"?>
<fantasy_content xml:lang="en-US" yahoo:uri="http://fantasysports.yahooapis.com/fantasy/v2/game/nfl" time="23.358106613159ms" copyright="Data provided by Yahoo! and STATS, LLC" refresh_rate="60" xmlns:yahoo="http://www.yahooapis.com/v1/base.rng" xmlns="http://fantasysports.yahooapis.com/fantasy/v2/base.rng">
 <game>
  <game_key>390</game_key>
  <game_id>390</game_id>
  <name>Football</name>
  <code>nfl</code>
  <type>full</type>
  <url>https://football.fantasysports.yahoo.com/f1</url>
  <season>2019</season>
  <is_registration_over>0</is_registration_over>
  <is_game_over>0</is_game_over>
  <is_offseason>0</is_offseason>
  <is_live_draft_lobby_active>1</is_live_draft_lobby_active>
 </game>
</fantasy_content>
```

I'll update it soon to have the 2019 league key `390`.

As for changes to code structs/endpoints, I haven't noticed any changes but have also not done extensive testing. Let me know if you have any issues there.

**Comment by ackleymi** [comment]
I'll poke around and let you know here if I find anything
